[Logging]
EnableLogging=true
SynchronousMode=false
HideSensitiveInformation=true
; Console Target
EnableConsole=true
ConsoleIncludeTimestamps=true
ConsoleMinLevel=0
ConsoleMaxLevel=5
; File Target
EnableFile=true
FileIncludeTimestamps=true
FileMinLevel=0
FileMaxLevel=5

[Frontend]
; BindIP has to be an IP address. PublicAddress can be an IP or a URL (e.g. fes2.marvelheroes.com)
BindIP=192.168.1.9
Port=4306
PublicAddress=193.237.201.24

[Auth]
Address=192.168.1.9
Port=8080
EnableWebApi=true

[PlayerManager]
BypassAuth=false
AllowClientVersionMismatch=false
SimulateQueue=false
QueuePlaceInLine=2023
QueueNumberOfPlayersInLine=9001
ShowNewsOnLogin=false
NewsUrl=http://localhost/

[DefaultPlayerData]
; Player Data for the default account that is used when BypassAuth is set to true
PlayerName=Player
StartingRegion=Regions/HUBRevamp/NPEAvengersTowerHUBRegion.prototype
StartingWaypoint=Waypoints/HUBS/NPEAvengersTowerHub.prototype
StartingAvatar=Entity/Characters/Avatars/Shipping/BlackCat.prototype
; Default AOIVolume is 3200. Set to 3800 when using Custom Max Camera Distance
AOIVolume=3200

[GroupingManager]
MotdPlayerName=MHEmutestUK
MotdText=A MHServerEmu powered Marvel Heroes testing server! Type !commands to see a list of available commands. Type !tower to return to Avengers Tower.
MotdPrestigeLevel=6

[GameData]
LoadAllPrototypes=false
UseEquipmentSlotTableCache=false

[GameOptions]
TeamUpSystemEnabled=true
AchievementsEnabled=true
OmegaMissionsEnabled=true
VeteranRewardsEnabled=true
MultiSpecRewardsEnabled=true
GiftingEnabled=true
CharacterSelectV2Enabled=true
CommunityNewsV2Enabled=true
LeaderboardsEnabled=true
NewPlayerExperienceEnabled=true
MissionTrackerV2Enabled=true
GiftingAccountAgeInDaysRequired=7
GiftingAvatarLevelRequired=20
GiftingLoginCountRequired=5
; Disabling Infinity replaces it with Omega
InfinitySystemEnabled=true
ChatBanVoteAccountAgeInDaysRequired=7
ChatBanVoteAvatarLevelRequired=20
ChatBanVoteLoginCountRequired=5
IsDifficultySliderEnabled=true
OrbisTrophiesEnabled=true

[CustomGameOptions]
RegionCleanupIntervalMS=300000
RegionUnvisitedThresholdMS=300000
WorldEntityRespawnTimeMS=30000

[Billing]
CurrencyBalance=9000
ApplyCatalogPatch=true
OverrideStoreUrls=true

; Set OverrideStoreUrls to true for these to work
StoreHomePageUrl=https://mhemutest.uk/store/index.html
StoreHomeBannerPageUrl=https://mhemutest.uk/store/images/banner.png
StoreHeroesBannerPageUrl=http://storecdn.marvelheroes.com/cdn/en_us/heroes_banner
StoreCostumesBannerPageUrl=http://storecdn.marvelheroes.com/cdn/en_us/costumes_banner
StoreBoostsBannerPageUrl=http://storecdn.marvelheroes.com/cdn/en_us/boosts_banner
StoreChestsBannerPageUrl=http://storecdn.marvelheroes.com/cdn/en_us/chests_banner
StoreSpecialsBannerPageUrl=http://storecdn.marvelheroes.com/cdn/en_us/specials_banner
StoreRealMoneyUrl=https://mhemutest.uk/store/gs-bundles.html
